wordpress:
    image: wordpress
    links:
        - wordpress_db:mysql
    ports:
        - 8180:80
wordpress_db:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: edureka
phpmyadmin:
    image: corbinu/docker-phpmyadmin
    environment:
        MYSQL_ROOT_PASSWORD: edureka
        MYSQL_USERNAME: root
    links:
        - wordpress_db:mysql
    ports:
        - 8181:80
      